#!/usr/bin/env python3
"""
Application Stack Traceroute v3.0 - Intelligent Reconstruction
Next-Generation Infrastructure Analysis with Progressive Discovery

FEATURES:
- Progressive stack reconstruction with header timeline analysis
- Adaptive fingerprinting based on discovered components
- Confidence scoring system for accurate identification
- Intelligent bypass generation targeting real forbidden endpoints
- Full correlation: CDN→WAF→LB→Proxy→Backend
- JSON export for orchestration tools

AUTHOR: Rewritten from scratch for bug bounty hunting
LICENSE: Use responsibly - authorized testing only
"""

import requests
import asyncio
import aiohttp
import json
import time
import base64
import urllib.parse
import re
import random
import string
import socket
import ssl
from collections import defaultdict
from datetime import datetime
from urllib.parse import urlparse, urljoin
from typing import Dict, List, Optional, Tuple
import urllib3
import warnings

# Suppress SSL warnings for security testing
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
warnings.filterwarnings('ignore', message='Unverified HTTPS request')


class ProgressiveStackAnalyzer:
    """
    Analyzes infrastructure stack progressively using header timeline,
    behavioral testing, and timing analysis for accurate reconstruction.
    """
    
    def __init__(self, target_url: str):
        self.target_url = target_url.rstrip('/')
        self.parsed_url = urlparse(target_url)
        self.session = requests.Session()
        self.session.verify = False
        
        # Stack reconstruction data
        self.stack = {
            'layers': [],           # Ordered list of discovered layers
            'timeline': [],         # Header processing timeline
            'confidence': {},       # Confidence scores per component
            'correlations': []      # Layer relationships
        }
        
        # Fingerprint data (YOU will populate this)
        self.fingerprints = self.initialize_fingerprints()
        
    def initialize_fingerprints(self) -> Dict:
        """
        Initialize comprehensive fingerprint signatures for all stack types.
        Optimized from v2.8 refactored - only essential patterns.
        """
        return {
            'cdn_detection': {
                'cloudflare': {
                    'headers': ['cf-ray', 'cf-cache-status', 'cf-request-id', 'cf-connecting-ip'],
                    'body_patterns': ['cloudflare', 'cf-ray', 'ray id:', 'checking your browser'],
                    'behavioral_paths': ['/cdn-cgi/trace', '/cdn-cgi/'],
                    'timing_signature': {'avg_ms': 30, 'jitter': 15}
                },
                'aws_cloudfront': {
                    'headers': ['x-amz-cf-id', 'x-amz-cf-pop', 'x-amzn-trace-id'],
                    'body_patterns': ['cloudfront', 'generated by cloudfront'],
                    'behavioral_paths': [],
                    'timing_signature': {'avg_ms': 40, 'jitter': 20}
                },
                'fastly': {
                    'headers': ['x-served-by', 'x-cache-hits', 'fastly-debug-digest', 'x-timer'],
                    'body_patterns': ['fastly error', 'varnish', 'fastly shield'],
                    'behavioral_paths': [],
                    'timing_signature': {'avg_ms': 35, 'jitter': 18}
                },
                'akamai': {
                    'headers': ['akamai-origin-hop', 'akamai-cache-status', 'true-client-ip'],
                    'body_patterns': ['akamai', 'reference #', 'ghost ip'],
                    'behavioral_paths': [],
                    'timing_signature': {'avg_ms': 45, 'jitter': 22}
                },
                'azure_cdn': {
                    'headers': ['x-azure-ref', 'x-msedge-ref', 'x-azure-fdid'],
                    'body_patterns': ['azure cdn', 'microsoft azure'],
                    'behavioral_paths': [],
                    'timing_signature': {'avg_ms': 50, 'jitter': 25}
                },
                'maxcdn': {
                    'headers': ['x-maxcdn-pop', 'x-sp-edge-pop'],
                    'body_patterns': ['maxcdn', 'netdna', 'stackpath'],
                    'behavioral_paths': [],
                    'timing_signature': {'avg_ms': 40, 'jitter': 20}
                }
            },

            'waf_detection': {
                'cloudflare_waf': {
                    'headers': ['cf-ray', 'cf-mitigated'],
                    'body_patterns': ['cloudflare', 'ray id:', 'error 1020', 'error 1006'],
                    'response_codes': [403, 503, 520]
                },
                'aws_waf': {
                    'headers': ['x-amzn-waf-action', 'x-amz-apigw-id'],
                    'body_patterns': ['aws waf', 'forbidden'],
                    'response_codes': [403]
                },
                'imperva': {
                    'headers': ['x-iinfo'],
                    'body_patterns': ['incapsula', 'imperva', 'visid_incap'],
                    'response_codes': [403]
                },
                'sucuri': {
                    'headers': ['x-sucuri-id', 'x-sucuri-cache'],
                    'body_patterns': ['sucuri', 'access denied'],
                    'response_codes': [403]
                },
                'f5_asm': {
                    'headers': ['x-wa-info'],
                    'body_patterns': ['f5', 'bigip', 'the requested url was rejected'],
                    'response_codes': [403]
                },
                'akamai': {
                    'headers': ['akamai-origin-hop', 'akamai-transformed', 'x-akamai-transformed'],
                    'response_codes': [403, 429],
                    'body_patterns': ['akamai', 'reference #', 'akamai ghost'],
                },
                'imperva_incapsula': {
                    'headers': ['x-iinfo', 'x-cdn'],
                    'response_codes': [403, 406, 429],
                    'body_patterns': ['incapsula', 'imperva', 'request unsuccessful'],
                },
                'f5_asm': {
                    'headers': ['x-f5-bigip', 'f5-bigip', 'bigip'],
                    'response_codes': [403, 406],
                    'body_patterns': ['f5', 'bigip', 'the requested url was rejected'],
                },
                'barracuda': {
                    'headers': ['x-barracuda-url', 'x-barra-counter'],
                    'response_codes': [403, 404],
                    'body_patterns': ['barracuda', 'barra', 'blocked by barracuda'],
                },
                'citrix_netscaler': {
                    'headers': ['ns_af', 'citrix_ns_id', 'netscaler'],
                    'response_codes': [403],
                    'body_patterns': ['netscaler', 'citrix', 'access denied'],
              },
                'fortinet_fortiweb': {
                   'headers': ['x-forwarded-for'],
                    'response_codes': [403],
                    'body_patterns': ['fortinet', 'fortigate', 'fortiweb', 'blocked by fortinet'],
                },
                'checkpoint_cloudguard': {
                    'headers': ['cp_session_id'],
                    'response_codes': [403],
                    'body_patterns': ['checkpoint', 'cloudguard', 'access denied'],
                },
                # Open Source WAFs
                'modsecurity': {
                    'headers': ['mod_security', 'modsec'],
                    'response_codes': [403, 406, 501],
                    'body_patterns': ['mod_security', 'modsecurity', 'not acceptable'],
                },
                'nginx_naxsi': {
                    'headers': ['naxsi/waf'],
                    'response_codes': [403, 418],
                    'body_patterns': ['naxsi', 'unusual request'],
                },
                    
                    # Specialized/Security-focused WAFs
                    'sucuri': {
                        'headers': ['x-sucuri-id', 'x-sucuri-cache'],
                        'cookies': ['sucuri_cloudproxy_uuid_'],
                        'response_codes': [403],
                        'body_patterns': ['sucuri', 'access denied', 'blocked by sucuri'],
                        'error_pages': ['access denied', 'questions?']
                    },
                    'wordfence': {
                        'headers': [],
                        'cookies': ['wfwaf-authcookie'],
                        'response_codes': [403, 503],
                        'body_patterns': ['wordfence', 'generated by wordfence'],
                        'error_pages': ['this response was generated by wordfence', 'your access to this site']
                    },
                    'wallarm': {
                        'headers': ['x-wallarm-mode'],
                        'cookies': [],
                        'response_codes': [403],
                        'body_patterns': ['wallarm', 'blocked by wallarm'],
                        'error_pages': ['request blocked']
                    },
                    'radware': {
                        'headers': ['x-defended-by'],
                        'cookies': ['rdx'],
                        'response_codes': [403],
                        'body_patterns': ['radware', 'application firewall'],
                        'error_pages': ['unauthorized request blocked']
                    },
                    'edgecast': {
                        'headers': ['server: ecs'],
                        'cookies': [],
                        'response_codes': [403, 400],
                        'body_patterns': ['edgecast', 'unauthorized request'],
                        'error_pages': ['unauthorized request']
                    },
                    'alert_logic': {
                        'headers': ['al_sess', 'al_lb'],
                        'cookies': ['al_sess'],
                        'response_codes': [403],
                        'body_patterns': ['alert logic', 'alertlogic'],
                        'error_pages': ['access denied']
                    },
                    'approach': {
                        'headers': ['approach'],
                        'cookies': [],
                        'response_codes': [403],
                        'body_patterns': ['approach', 'blocked by approach'],
                        'error_pages': ['blocked by approach']
                    },
                    'armor': {
                        'headers': ['armor'],
                        'cookies': [],
                        'response_codes': [403],
                        'body_patterns': ['armor defense'],
                        'error_pages': ['blocked by armor']
                    },
                    'aws_elb': {
                        'headers': ['awsalb', 'awsalbcors'],
                        'cookies': ['awsalb', 'awsalbcors'],
                        'response_codes': [403, 503],
                        'body_patterns': ['aws', 'application load balancer'],
                        'error_pages': ['service temporarily unavailable']
                    },
                    'baidu_yunjiasu': {
                        'headers': ['yunjiasu-nginx'],
                        'cookies': [],
                        'response_codes': [403],
                        'body_patterns': ['yunjiasu', 'baidu'],
                        'error_pages': ['blocked by yunjiasu']
                    },
                    'bekchy': {
                        'headers': ['bekchy - backend server'],
                        'cookies': [],
                        'response_codes': [403],
                        'body_patterns': ['bekchy'],
                        'error_pages': ['blocked by bekchy']
                    },
                    'binarysec': {
                        'headers': ['binarysec'],
                        'cookies': [],
                        'response_codes': [403, 400],
                        'body_patterns': ['binarysec', 'blocked by binarysec'],
                        'error_pages': ['request blocked by binarysec']
                    },
                    'blockdos': {
                        'headers': ['blockdos.net'],
                        'cookies': [],
                        'response_codes': [403],
                        'body_patterns': ['blockdos', 'you have been blocked'],
                        'error_pages': ['you have been blocked']
                    },
                    'cerber': {
                        'headers': [],
                        'cookies': [],
                        'response_codes': [403],
                        'body_patterns': ['cerber security', 'access denied'],
                        'error_pages': ['we are sorry, but this page is blocked', 'cerber security']
                    },
                    'chinacache': {
                        'headers': ['powered-by-chinacache'],
                        'cookies': [],
                        'response_codes': [403],
                        'body_patterns': ['chinacache'],
                        'error_pages': ['blocked by chinacache']
                    },
                    'cloudbric': {
                        'headers': ['x-cloudbric-request-id'],
                        'cookies': [],
                        'response_codes': [403],
                        'body_patterns': ['cloudbric', 'blocked by cloudbric'],
                        'error_pages': ['malicious/abnormal request blocked']
                    },
                    'comodo': {
                        'headers': ['protected-by', 'server: cwaf'],
                        'cookies': [],
                        'response_codes': [403],
                        'body_patterns': ['comodo', 'protected by comodo waf'],
                        'error_pages': ['access denied']
                    },
                    'deny_all': {
                        'headers': ['sessioncookie'],
                        'cookies': ['sessioncookie'],
                        'response_codes': [403],
                        'body_patterns': ['denyall', 'condition intercepted'],
                        'error_pages': ['condition intercepted']
                    },
                    'dotdefender': {
                        'headers': ['x-dotdefender-denied'],
                        'cookies': [],
                        'response_codes': [403],
                        'body_patterns': ['dotdefender', 'applicure dotdefender'],
                        'error_pages': ['dotdefender blocked your request']
                    },
                    'hyperguard': {
                        'headers': ['hyperguard'],
                        'cookies': [],
                        'response_codes': [403],
                        'body_patterns': ['hyperguard', 'unauthorized request blocked'],
                        'error_pages': ['unauthorized request blocked']
                    },
                    'jiasule': {
                        'headers': ['jiasule-waf'],
                        'cookies': ['jsluid', '__jsluid'],
                        'response_codes': [403, 400],
                        'body_patterns': ['jiasule', 'static.jiasule.com'],
                        'error_pages': ['notice-jiasule']
                    },
                    'knownsec': {
                        'headers': ['ks-waf'],
                        'cookies': [],
                        'response_codes': [403, 555],
                        'body_patterns': ['knownsec', 'ks-waf', 'blocked by knownsec'],
                        'error_pages': ['request denied by knownsec']
                    },
                    'malcare': {
                        'headers': [],
                        'cookies': [],
                        'response_codes': [403],
                        'body_patterns': ['malcare', 'firewall', 'blocked by malcare'],
                        'error_pages': ['blocked because of malicious activities']
                    },
                    'newdefend': {
                        'headers': ['newdefend'],
                        'cookies': [],
                        'response_codes': [403, 412],
                        'body_patterns': ['newdefend', 'request blocked'],
                        'error_pages': ['request blocked']
                    },
                    'nsfocus': {
                        'headers': ['nsfocus'],
                        'cookies': [],
                        'response_codes': [403],
                        'body_patterns': ['nsfocus', 'blocked by nsfocus'],
                        'error_pages': ['blocked by nsfocus waf']
                    },
                    'palo_alto': {
                        'headers': ['server: pa-vm'],
                        'cookies': [],
                        'response_codes': [403],
                        'body_patterns': ['palo alto', 'pan-os'],
                        'error_pages': ['access denied']
                    },
                    'profense': {
                        'headers': ['profense'],
                        'cookies': [],
                        'response_codes': [403, 406],
                        'body_patterns': ['profense', 'plixer'],
                        'error_pages': ['request blocked by profense']
                    },
                    'reblaze': {
                        'headers': ['rbzid'],
                        'cookies': ['rbzid'],
                        'response_codes': [403],
                        'body_patterns': ['reblaze', 'current request blocked'],
                        'error_pages': ['current request blocked']
                    },
                    'safe3': {
                        'headers': ['safe3waf'],
                        'cookies': [],
                        'response_codes': [403],
                        'body_patterns': ['safe3', 'safe3 web application firewall'],
                        'error_pages': ['safe3 web application firewall']
                    },
                    'safedog': {
                        'headers': ['server: safedog', 'safedog'],
                        'cookies': ['safedog-flow-item'],
                        'response_codes': [403, 404, 405],
                        'body_patterns': ['safedog', 'wangzhan', '404 not found'],
                        'error_pages': ['404 not found']
                    },
                    'secupress': {
                        'headers': [],
                        'cookies': [],
                        'response_codes': [403],
                        'body_patterns': ['secupress', 'blocked by secupress'],
                        'error_pages': ['cool, you are totally forbidden']
                    },
                    'securi': {
                        'headers': ['x-sucuri-id'],
                        'cookies': ['sucuri_cloudproxy_uuid'],
                        'response_codes': [403],
                        'body_patterns': ['sucuri', 'cloudproxy'],
                        'error_pages': ['access denied']
                    },
                    'senginx': {
                        'headers': ['senginx'],
                        'cookies': [],
                        'response_codes': [403],
                        'body_patterns': ['senginx', 'blocked by senginx'],
                        'error_pages': ['blocked by senginx']
                    },
                    'shadow_daemon': {
                        'headers': ['shadowd_ui'],
                        'cookies': [],
                        'response_codes': [403],
                        'body_patterns': ['shadowd', 'shadow daemon'],
                        'error_pages': ['request blocked by shadow daemon']
                    },
                    'shieldsecurity': {
                        'headers': [],
                        'cookies': ['icwp-wpsf'],
                        'response_codes': [403],
                        'body_patterns': ['shield security', 'icwp'],
                        'error_pages': ['you were blocked by the shield']
                    },
                    'sonicwall': {
                        'headers': ['sonicwall'],
                        'cookies': [],
                        'response_codes': [403],
                        'body_patterns': ['sonicwall', 'this request is blocked'],
                        'error_pages': ['this request is blocked by sonicwall']
                    },
                    'sophos': {
                        'headers': ['spdy'],
                        'cookies': [],
                        'response_codes': [403],
                        'body_patterns': ['sophos', 'blocked by sophos'],
                        'error_pages': ['blocked by sophos utm']
                    },
                    'stingray': {
                        'headers': ['x-mapping'],
                        'cookies': [],
                        'response_codes': [403, 500],
                        'body_patterns': ['stingray', 'riverbed stingray'],
                        'error_pages': ['request rejected']
                    },
                    'tencent_cloud': {
                        'headers': ['server: tencent-cls'],
                        'cookies': [],
                        'response_codes': [403],
                        'body_patterns': ['tencent', 'qcloud'],
                        'error_pages': ['blocked by tencent cloud waf']
                    },
                    'usp_secure_entry': {
                        'headers': ['usp-se'],
                        'cookies': [],
                        'response_codes': [403],
                        'body_patterns': ['usp secure entry server'],
                        'error_pages': ['request denied by usp secure entry server']
                    },
                    'varnish': {
                        'headers': ['x-varnish', 'via'],
                        'cookies': [],
                        'response_codes': [403, 503],
                        'body_patterns': ['varnish', 'guru meditation'],
                        'error_pages': ['guru meditation', 'varnish cache server']
                    },
                    'webknight': {
                        'headers': ['webknight'],
                        'cookies': [],
                        'response_codes': [403, 999],
                        'body_patterns': ['webknight', 'http error 999'],
                        'error_pages': ['blocked by webknight']
                    },
                    'yundun': {
                        'headers': ['server: yundun'],
                        'cookies': ['yunsuo_session'],
                        'response_codes': [403],
                        'body_patterns': ['yundun', 'blocked by yundun'],
                        'error_pages': ['blocked by yundun']
                    },
                    'zenedge': {
                        'headers': ['x-zen-fury'],
                        'cookies': [],
                        'response_codes': [403],
                        'body_patterns': ['zenedge', 'request blocked'],
                        'error_pages': ['request has been blocked']
                    }

            },

            'load_balancer_detection': {
                'haproxy': {
                    'headers': ['x-haproxy'],
                    'body_patterns': ['haproxy'],
                    'behavioral_paths': ['/haproxy?stats']
                },
                'nginx_lb': {
                    'headers': ['x-nginx-lb', 'x-upstream-addr'],
                    'body_patterns': ['nginx'],
                    'behavioral_paths': ['/nginx_status']
                },
                'aws_alb': {
                    'headers': ['x-aws-alb-target-group-arn', 'x-amzn-trace-id'],
                    'body_patterns': ['application load balancer'],
                    'behavioral_paths': []
                },
                'azure_lb': {
                    'headers': ['x-azure-ref'],
                    'body_patterns': ['azure load balancer'],
                    'behavioral_paths': []
                }
            },

            'proxy_detection': {
                'varnish': {
                    'headers': ['x-varnish', 'via'],
                    'body_patterns': ['varnish'],
                    'behavioral_paths': ['/varnish-status']
                },
                'squid': {
                    'headers': ['x-squid', 'via'],
                    'body_patterns': ['squid'],
                    'behavioral_paths': []
                },
                'nginx_proxy': {
                    'headers': ['x-nginx-proxy', 'via'],
                    'body_patterns': ['nginx'],
                    'behavioral_paths': []
                }
            },

            'api_gateway_detection': {
                'kong': {
                    'headers': ['x-kong', 'x-kong-proxy-latency'],
                    'body_patterns': ['kong gateway'],
                    'behavioral_paths': ['/']
                },
                'aws_api_gateway': {
                    'headers': ['x-amazon-apigateway', 'x-amzn-requestid'],
                    'body_patterns': ['amazon api gateway'],
                    'behavioral_paths': []
                },
                'azure_apim': {
                    'headers': ['x-azure-apim'],
                    'body_patterns': ['azure api management'],
                    'behavioral_paths': []
                }
            },

            'service_mesh_detection': {
                'istio': {
                    'headers': ['x-envoy', 'x-istio-attributes', 'x-b3-traceid'],
                    'body_patterns': ['envoy', 'istio'],
                    'behavioral_paths': ['/stats', '/ready']
                },
                'linkerd': {
                    'headers': ['l5d-dst-service', 'x-linkerd'],
                    'body_patterns': ['linkerd'],
                    'behavioral_paths': []
                }
            },

            'serverless_detection': {
                'aws_lambda': {
                    'headers': ['x-amzn-requestid', 'x-amzn-trace-id', 'x-lambda-request-id'],
                    'body_patterns': ['lambda', 'function invocation'],
                    'behavioral_paths': []
                },
                'google_cloud_functions': {
                    'headers': ['function-execution-id', 'x-cloud-trace-context'],
                    'body_patterns': ['cloud functions'],
                    'behavioral_paths': []
                },
                'azure_functions': {
                    'headers': ['x-azure-requestid', 'x-ms-request-id'],
                    'body_patterns': ['azure functions'],
                    'behavioral_paths': []
                }
            },

            'container_orchestration_detection': {
                'kubernetes': {
                    'headers': ['x-kubernetes', 'x-k8s', 'x-pod-name', 'x-namespace'],
                    'body_patterns': ['kubernetes', 'k8s'],
                    'behavioral_paths': ['/healthz', '/readyz', '/livez']
                },
                'docker': {
                    'headers': ['x-docker', 'x-container-id'],
                    'body_patterns': ['docker', 'container id'],
                    'behavioral_paths': []
                },
                'aws_ecs': {
                    'headers': ['x-ecs-task', 'x-amzn-trace-id'],
                    'body_patterns': ['ecs task', 'fargate'],
                    'behavioral_paths': []
                }
            },

            'database_proxy_detection': {
                'pgbouncer': {
                    'headers': [],
                    'body_patterns': ['pgbouncer'],
                    'behavioral_paths': [],
                    'response_codes': []
                },
                'mysql_proxy': {
                    'headers': [],
                    'body_patterns': ['mysql proxy'],
                    'behavioral_paths': [],
                    'response_codes': []
                },
                'redis_sentinel': {
                    'headers': [],
                    'body_patterns': ['redis sentinel'],
                    'behavioral_paths': [],
                    'response_codes': []
                },
                'mongodb_proxy': {
                    'headers': [],
                    'body_patterns': ['mongodb proxy'],
                    'behavioral_paths': [],
                    'response_codes': []
                }
            },

            'cache_layer_detection': {
                'redis': {
                    'headers': ['x-redis-cache'],
                    'body_patterns': ['redis'],
                    'behavioral_paths': []
                },
                'memcached': {
                    'headers': ['x-memcached'],
                    'body_patterns': ['memcached'],
                    'behavioral_paths': []
                },
                'varnish_cache': {
                    'headers': ['x-varnish', 'x-cache'],
                    'body_patterns': ['varnish'],
                    'behavioral_paths': []
                }
            },

            'microservice_detection': {
                'spring_boot': {
                    'headers': ['x-application-context'],
                    'body_patterns': ['spring boot', 'whitelabel error page'],
                    'behavioral_paths': ['/actuator/health', '/actuator/info']
                },
                'nodejs_express': {
                    'headers': ['x-powered-by'],
                    'body_patterns': ['express'],
                    'behavioral_paths': []
                }
            }
        }
    
    def log(self, category: str, message: str, level: str = "INFO"):
        """Structured logging"""
        timestamp = time.strftime('%H:%M:%S')
        icons = {"INFO": "ℹ️", "SUCCESS": "✅", "WARNING": "⚠️", "ERROR": "❌", "DISCOVERY": "🔍"}
        print(f"[{timestamp}] {icons.get(level, '•')} [{category}] {message}")
    
    def send_baseline_request(self) -> requests.Response:
        """Send initial request to analyze raw stack response"""
        headers = {
            'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:140.0) Gecko/20100101 Firefox/140.0',
            'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Accept-Language': 'en-US,en;q=0.5',
            'Accept-Encoding': 'gzip, deflate, br',
            'DNT': '1',
            'Connection': 'keep-alive',
            'Upgrade-Insecure-Requests': '1'
        }
        
        response = self.session.get(self.target_url, headers=headers, timeout=15)
        return response
    
    def analyze_header_timeline(self, response: requests.Response) -> List[Dict]:
        """
        Analyze header timeline to reconstruct processing chain.
        Via, X-Forwarded-*, Server headers reveal the path.
        """
        timeline = []
        
        # Via header analysis (shows proxy chain)
        via_header = response.headers.get('Via', '')
        if via_header:
            hops = via_header.split(',')
            for idx, hop in enumerate(hops):
                hop = hop.strip()
                timeline.append({
                    'order': idx,
                    'type': 'proxy',
                    'raw': hop,
                    'component': self._identify_from_via(hop)
                })
        
        # X-Forwarded headers
        xff = response.headers.get('X-Forwarded-For', '')
        if xff:
            timeline.append({
                'order': len(timeline),
                'type': 'proxy/lb',
                'raw': f'X-Forwarded-For: {xff}',
                'component': 'forwarding_proxy'
            })
        
        # Server header (usually last in chain - origin)
        server = response.headers.get('Server', '')
        if server:
            timeline.append({
                'order': len(timeline),
                'type': 'backend',
                'raw': f'Server: {server}',
                'component': self._identify_from_server(server)
            })
        
        # CDN-specific headers (usually first in chain)
        cdn_headers = {
            'CF-Ray': 'cloudflare',
            'X-Amz-Cf-Id': 'cloudfront',
            'X-Served-By': 'fastly/akamai',
            'X-Cache': 'generic_cdn'
        }
        
        for header, cdn_type in cdn_headers.items():
            if header in response.headers:
                timeline.insert(0, {  # CDN is always first
                    'order': 0,
                    'type': 'cdn',
                    'raw': f'{header}: {response.headers[header]}',
                    'component': cdn_type
                })
                break
        
        # WAF-specific headers
        waf_headers = {
            'X-WAF-Event-Info': 'generic_waf',
            'X-Sucuri-ID': 'sucuri_waf',
            'X-Denied-Reason': 'generic_waf'
        }
        
        for header, waf_type in waf_headers.items():
            if header in response.headers:
                # WAF usually after CDN but before backend
                insert_pos = 1 if timeline and timeline[0]['type'] == 'cdn' else 0
                timeline.insert(insert_pos, {
                    'order': insert_pos,
                    'type': 'waf',
                    'raw': f'{header}: {response.headers[header]}',
                    'component': waf_type
                })
                break
        
        self.stack['timeline'] = timeline
        return timeline
    
    def _identify_from_via(self, via_string: str) -> str:
        """Identify component from Via header"""
        via_lower = via_string.lower()
        
        identifiers = {
            'cloudflare': 'cloudflare',
            'nginx': 'nginx_proxy',
            'squid': 'squid_proxy',
            'varnish': 'varnish_cache',
            'haproxy': 'haproxy_lb',
            'envoy': 'envoy_proxy'
        }
        
        for pattern, component in identifiers.items():
            if pattern in via_lower:
                return component
        
        return 'unknown_proxy'
    
    def _identify_from_server(self, server_string: str) -> str:
        """Identify backend from Server header"""
        server_lower = server_string.lower()
        
        identifiers = {
            'nginx': 'nginx_backend',
            'apache': 'apache_backend',
            'microsoft-iis': 'iis_backend',
            'cloudflare': 'cloudflare_workers',
            'openresty': 'openresty_backend'
        }
        
        for pattern, component in identifiers.items():
            if pattern in server_lower:
                return component
        
        return 'unknown_backend'
    
    def progressive_fingerprinting(self, baseline_response: requests.Response):
        """
        Progressive fingerprinting: start with timeline analysis,
        then deep-dive into each discovered layer type.
        """
        self.log("FINGERPRINTING", "Starting progressive stack analysis...", "INFO")
        
        # Phase 1: Timeline analysis (already done)
        timeline = self.stack['timeline']
        
        # Phase 2: Deep fingerprinting for each layer type found
        layer_types = set([layer['type'] for layer in timeline])
        
        for layer_type in layer_types:
            if layer_type == 'cdn':
                self.deep_cdn_fingerprinting(baseline_response)
            elif layer_type == 'waf':
                self.deep_waf_fingerprinting(baseline_response)
            elif layer_type == 'proxy' or layer_type == 'proxy/lb':
                self.deep_proxy_fingerprinting(baseline_response)
            elif layer_type == 'backend':
                self.deep_backend_fingerprinting(baseline_response)
        
        # Phase 3: Check for hidden layers (no header evidence)
        self.detect_hidden_layers()
    
    def deep_cdn_fingerprinting(self, response: requests.Response):
        """
        Deep CDN analysis using ALL data from fingerprint list.
        Confidence scoring: Headers(40) + Body(30) + Behavioral(20) + Timing(10)
        """
        self.log("CDN", "Deep fingerprinting with confidence scoring...", "DISCOVERY")
        
        cdn_fingerprints = self.fingerprints['cdn_detection']
        detected = []
        
        for cdn_name, fingerprint_data in cdn_fingerprints.items():
            confidence = 0
            evidence = []
            
            # YOU will have these keys in your fingerprint:
            # 'headers', 'body_patterns', 'behavioral_paths', 'timing_signature'
            
            # 1. Header matching (40 points)
            headers_list = fingerprint_data.get('headers', [])
            for header_pattern in headers_list:
                for header_name, header_value in response.headers.items():
                    if re.search(header_pattern, f"{header_name}: {header_value}", re.IGNORECASE):
                        confidence += 40
                        evidence.append(f"Header: {header_name}")
                        break
                if confidence >= 40:
                    break
            
            # 2. Body pattern matching (30 points)
            body_patterns = fingerprint_data.get('body_patterns', [])
            response_text = response.text.lower()
            for pattern in body_patterns:
                if pattern.lower() in response_text:
                    confidence += 30
                    evidence.append(f"Body pattern: {pattern}")
                    break
            
            # 3. Behavioral testing (20 points)
            behavioral_paths = fingerprint_data.get('behavioral_paths', [])
            for path in behavioral_paths:
                try:
                    test_url = self.target_url + path
                    test_response = self.session.get(test_url, timeout=5)
                    # If path exists or returns specific code, it's behavioral evidence
                    if test_response.status_code in [200, 403, 404]:  # Existence check
                        confidence += 20
                        evidence.append(f"Behavioral: {path}")
                        break
                except:
                    pass
            
            # 4. Timing analysis (10 points)
            timing_sig = fingerprint_data.get('timing_signature', {})
            if timing_sig:
                avg_latency = self._measure_latency()
                expected_ms = timing_sig.get('avg_ms', 0)
                jitter = timing_sig.get('jitter', 50)
                
                if abs(avg_latency - expected_ms) <= jitter:
                    confidence += 10
                    evidence.append(f"Timing: ~{avg_latency}ms")
            
            # Store if confidence is sufficient
            if confidence >= 40:  # Minimum threshold
                detected.append({
                    'name': cdn_name,
                    'confidence': confidence,
                    'evidence': evidence,
                    'level': 'HIGH' if confidence >= 70 else 'MEDIUM' if confidence >= 50 else 'LOW'
                })
        
        # Sort by confidence and add to stack
        detected.sort(key=lambda x: x['confidence'], reverse=True)
        
        if detected:
            best_match = detected[0]
            self.stack['layers'].append({
                'type': 'CDN',
                'component': best_match['name'],
                'confidence': best_match['confidence'],
                'level': best_match['level'],
                'evidence': best_match['evidence']
            })
            self.log("CDN", f"Detected: {best_match['name']} (confidence: {best_match['confidence']}/100, {best_match['level']})", "SUCCESS")
        else:
            self.log("CDN", "No CDN detected or confidence too low", "INFO")
    
    def deep_waf_fingerprinting(self, response: requests.Response):
        """
        Deep WAF analysis with active testing.
        Uses malicious payloads to trigger WAF responses.
        """
        self.log("WAF", "Deep fingerprinting with active payload testing...", "DISCOVERY")
        
        waf_fingerprints = self.fingerprints['waf_detection']
        detected = []
        
        # Test payloads to trigger WAF
        test_payloads = [
            "/?test=<script>alert(1)</script>",
            "/?test=' OR '1'='1",
            "/?test=../../../etc/passwd",
            "/?test=<img src=x onerror=alert(1)>"
        ]
        
        for waf_name, fingerprint_data in waf_fingerprints.items():
            confidence = 0
            evidence = []
            
            # 1. Passive detection from baseline response (40 points)
            headers_list = fingerprint_data.get('headers', [])
            for header_pattern in headers_list:
                for header_name, header_value in response.headers.items():
                    if re.search(header_pattern, f"{header_name}: {header_value}", re.IGNORECASE):
                        confidence += 40
                        evidence.append(f"Header: {header_name}")
                        break
                if confidence >= 40:
                    break
            
            # 2. Active testing with payloads (30 points)
            block_patterns = fingerprint_data.get('block_patterns', [])
            for payload in test_payloads:
                try:
                    test_url = self.target_url + payload
                    test_response = self.session.get(test_url, timeout=5)
                    
                    # Check if response matches WAF block pattern
                    full_response = f"{test_response.status_code} {test_response.text}".lower()
                    for pattern in block_patterns:
                        if re.search(pattern, full_response, re.IGNORECASE):
                            confidence += 30
                            evidence.append(f"Block pattern: {pattern}")
                            break
                    
                    if confidence >= 70:
                        break
                except:
                    pass
            
            # 3. Response signature analysis (30 points)
            response_signatures = fingerprint_data.get('response_signatures', [])
            response_text = response.text.lower()
            for signature in response_signatures:
                if signature.lower() in response_text:
                    confidence += 30
                    evidence.append(f"Response signature: {signature}")
                    break
            
            if confidence >= 40:
                detected.append({
                    'name': waf_name,
                    'confidence': confidence,
                    'evidence': evidence,
                    'level': 'HIGH' if confidence >= 70 else 'MEDIUM' if confidence >= 50 else 'LOW'
                })
        
        detected.sort(key=lambda x: x['confidence'], reverse=True)
        
        if detected:
            best_match = detected[0]
            self.stack['layers'].append({
                'type': 'WAF',
                'component': best_match['name'],
                'confidence': best_match['confidence'],
                'level': best_match['level'],
                'evidence': best_match['evidence']
            })
            self.log("WAF", f"Detected: {best_match['name']} (confidence: {best_match['confidence']}/100, {best_match['level']})", "SUCCESS")
        else:
            self.log("WAF", "No WAF detected or confidence too low", "INFO")
    
    def deep_proxy_fingerprinting(self, response: requests.Response):
        """
        Deep Proxy/Load Balancer analysis.
        Similar pattern to CDN/WAF with confidence scoring.
        """
        self.log("PROXY", "Deep fingerprinting...", "DISCOVERY")
        
        proxy_fingerprints = self.fingerprints['proxy_detection']
        detected = []
        
        for proxy_name, fingerprint_data in proxy_fingerprints.items():
            confidence = 0
            evidence = []
            
            # Header analysis (40 points)
            headers_list = fingerprint_data.get('headers', [])
            for header_pattern in headers_list:
                for header_name, header_value in response.headers.items():
                    if re.search(header_pattern, f"{header_name}: {header_value}", re.IGNORECASE):
                        confidence += 40
                        evidence.append(f"Header: {header_name}")
                        break
                if confidence >= 40:
                    break
            
            # Via header specific analysis (30 points)
            via = response.headers.get('Via', '').lower()
            via_patterns = fingerprint_data.get('via_patterns', [])
            for pattern in via_patterns:
                if pattern.lower() in via:
                    confidence += 30
                    evidence.append(f"Via pattern: {pattern}")
                    break
            
            # Connection behavior (20 points)
            connection_tests = fingerprint_data.get('connection_tests', [])
            # YOU can add specific connection behavior tests here
            
            if confidence >= 40:
                detected.append({
                    'name': proxy_name,
                    'confidence': confidence,
                    'evidence': evidence,
                    'level': 'HIGH' if confidence >= 70 else 'MEDIUM'
                })
        
        detected.sort(key=lambda x: x['confidence'], reverse=True)
        
        if detected:
            best_match = detected[0]
            self.stack['layers'].append({
                'type': 'PROXY',
                'component': best_match['name'],
                'confidence': best_match['confidence'],
                'level': best_match['level'],
                'evidence': best_match['evidence']
            })
            self.log("PROXY", f"Detected: {best_match['name']} (confidence: {best_match['confidence']}/100)", "SUCCESS")
    
    def deep_backend_fingerprinting(self, response: requests.Response):
        """
        Deep Backend analysis (web server, runtime, framework).
        """
        self.log("BACKEND", "Deep fingerprinting...", "DISCOVERY")
        
        backend_fingerprints = self.fingerprints['backend_detection']
        detected = []
        
        for backend_name, fingerprint_data in backend_fingerprints.items():
            confidence = 0
            evidence = []
            
            # Server header (40 points)
            server = response.headers.get('Server', '').lower()
            server_patterns = fingerprint_data.get('server_patterns', [])
            for pattern in server_patterns:
                if pattern.lower() in server:
                    confidence += 40
                    evidence.append(f"Server: {pattern}")
                    break
            
            # Technology-specific headers (30 points)
            tech_headers = fingerprint_data.get('tech_headers', {})
            for header_name, expected_value in tech_headers.items():
                actual_value = response.headers.get(header_name, '')
                if expected_value.lower() in actual_value.lower():
                    confidence += 30
                    evidence.append(f"Tech header: {header_name}")
                    break
            
            # Framework detection from response (30 points)
            framework_patterns = fingerprint_data.get('framework_patterns', [])
            for pattern in framework_patterns:
                if re.search(pattern, response.text, re.IGNORECASE):
                    confidence += 30
                    evidence.append(f"Framework pattern: {pattern}")
                    break
            
            if confidence >= 40:
                detected.append({
                    'name': backend_name,
                    'confidence': confidence,
                    'evidence': evidence,
                    'level': 'HIGH' if confidence >= 70 else 'MEDIUM'
                })
        
        detected.sort(key=lambda x: x['confidence'], reverse=True)
        
        if detected:
            best_match = detected[0]
            self.stack['layers'].append({
                'type': 'BACKEND',
                'component': best_match['name'],
                'confidence': best_match['confidence'],
                'level': best_match['level'],
                'evidence': best_match['evidence']
            })
            self.log("BACKEND", f"Detected: {best_match['name']} (confidence: {best_match['confidence']}/100)", "SUCCESS")
    
    def detect_hidden_layers(self):
        """
        Detect layers that don't leave obvious headers.
        Uses timing analysis, behavioral testing, and edge cases.
        """
        self.log("HIDDEN", "Searching for hidden layers (API Gateway, Service Mesh, etc.)...", "DISCOVERY")
        
        # Check for API Gateway patterns
        api_paths = ['/api/', '/v1/', '/graphql', '/rest/']
        for path in api_paths:
            try:
                test_url = self.target_url + path
                test_response = self.session.get(test_url, timeout=5)
                
                # API Gateways often add specific headers on API paths
                gateway_headers = ['X-Kong-', 'X-Amzn-', 'X-Gateway-']
                for header_pattern in gateway_headers:
                    for header_name in test_response.headers.keys():
                        if header_pattern in header_name:
                            self.stack['layers'].append({
                                'type': 'API_GATEWAY',
                                'component': 'detected_via_api_path',
                                'confidence': 60,
                                'level': 'MEDIUM',
                                'evidence': [f'Header on {path}: {header_name}']
                            })
                            self.log("HIDDEN", f"API Gateway detected via {path}", "SUCCESS")
                            return
            except:
                pass
        
        # Timing-based detection for transparent proxies
        latencies = []
        for _ in range(3):
            start = time.time()
            try:
                self.session.get(self.target_url, timeout=5)
                latencies.append((time.time() - start) * 1000)
            except:
                pass
        
        if latencies:
            avg_latency = sum(latencies) / len(latencies)
            jitter = max(latencies) - min(latencies)
            
            # High jitter might indicate load balancing
            if jitter > 100:
                self.stack['layers'].append({
                    'type': 'LOAD_BALANCER',
                    'component': 'hidden_lb_via_timing',
                    'confidence': 50,
                    'level': 'LOW',
                    'evidence': [f'High jitter: {jitter:.2f}ms']
                })
                self.log("HIDDEN", f"Possible hidden load balancer (jitter: {jitter:.2f}ms)", "WARNING")
    
    def _measure_latency(self) -> float:
        """Measure average latency for timing analysis"""
        latencies = []
        for _ in range(3):
            start = time.time()
            try:
                self.session.head(self.target_url, timeout=5)
                latencies.append((time.time() - start) * 1000)
            except:
                pass
        return sum(latencies) / len(latencies) if latencies else 0
    
    def correlate_stack(self):
        """
        Correlate discovered layers to understand the full chain.
        Example: CDN → WAF → Load Balancer → Proxy → Backend
        """
        self.log("CORRELATION", "Building stack relationships...", "INFO")
        
        # Sort layers by typical order
        order_priority = {'CDN': 1, 'WAF': 2, 'API_GATEWAY': 3, 'LOAD_BALANCER': 4, 'PROXY': 5, 'BACKEND': 6}
        
        self.stack['layers'].sort(key=lambda x: order_priority.get(x['type'], 99))
        
        # Build correlations
        for i in range(len(self.stack['layers']) - 1):
            current = self.stack['layers'][i]
            next_layer = self.stack['layers'][i + 1]
            
            self.stack['correlations'].append({
                'from': f"{current['type']}:{current['component']}",
                'to': f"{next_layer['type']}:{next_layer['component']}",
                'relationship': 'forwards_to'
            })
        
        # Log the chain
        if self.stack['layers']:
            chain = " → ".join([f"{l['type']}({l['component']})" for l in self.stack['layers']])
            self.log("CORRELATION", f"Stack chain: {chain}", "SUCCESS")


class ForbiddenEndpointFinder:
    """
    Finds a real 403/401 forbidden endpoint for bypass testing.
    """
    
    def __init__(self, target_url: str, session: requests.Session):
        self.target_url = target_url.rstrip('/')
        self.session = session
    
    def find(self, user_provided: Optional[str] = None) -> Optional[str]:
        """Find forbidden endpoint"""
        print("\n🔍 Phase 0: Finding Forbidden Endpoint for Bypass Testing")
        print("=" * 70)
        
        # If user provided one, validate it
        if user_provided:
            if self._is_truly_forbidden(user_provided):
                print(f"  ✅ User-provided endpoint validated: {user_provided}")
                return user_provided
            else:
                print(f"  ⚠️ User-provided endpoint doesn't return 403/401, searching alternatives...")
        
        # Common forbidden paths
        common_paths = [
            '/admin', '/wp-admin', '/administrator', '/secure', '/api/admin',
            '/manage', '/console', '/portal', '/control', '/private',
            '/restricted', '/staff', '/backend', '/cpanel', '/webadmin',
            '/.env', '/.git', '/config', '/phpmyadmin', '/adminer',
            '/api/v1/admin', '/api/admin', '/admin.php', '/login',
            '/secret', '/internal', '/debug', '/test'
        ]
        
        print(f"  🔎 Testing {len(common_paths)} common forbidden paths...")
        
        for path in common_paths:
            url = self.target_url + path
            if self._is_truly_forbidden(url):
                print(f"  ✅ Found forbidden endpoint: {path}")
                return url
        
        print("  ⚠️ No forbidden endpoint found - bypass testing will be limited")
        return None
    
    def _is_truly_forbidden(self, url: str) -> bool:
        """Check if URL returns true 403/401 (not redirect)"""
        try:
            headers = {
                'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:140.0) Gecko/20100101 Firefox/140.0',
                'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'
            }
            
            response = self.session.get(url, headers=headers, timeout=5, allow_redirects=False)
            
            # True forbidden: 401/403 without redirect
            if response.status_code in [401, 403] and response.status_code != 302:
                return True
            
            return False
        except:
            return False


class DiscrepancyTester:
    """
    Tests for parser discrepancies between stack layers.
    CRITICAL: Uses the REAL forbidden endpoint, not hardcoded paths!
    """
    
    def __init__(self, target_url: str, forbidden_endpoint: str, session: requests.Session, stack_analyzer: ProgressiveStackAnalyzer):
        self.target_url = target_url.rstrip('/')
        self.forbidden_endpoint = forbidden_endpoint
        self.session = session
        self.stack_analyzer = stack_analyzer
        self.discrepancies = []
    
    def test_all_discrepancies(self):
        """Run all discrepancy tests on the REAL forbidden endpoint - EXPANDED"""
        print("\n🧪 Phase 3: Parser Discrepancy Testing")
        print("=" * 70)

        if not self.forbidden_endpoint:
            print("  ⚠️ No forbidden endpoint available - skipping discrepancy tests")
            return

        print(f"  🎯 Target: {self.forbidden_endpoint}")
        print(f"  📊 Testing against reconstructed stack: {len(self.stack_analyzer.stack['layers'])} layers")

        # Run all discrepancy test categories (EXPANDED: 7 categories)
        self.test_header_confusion()
        self.test_method_confusion()
        self.test_path_normalization()
        self.test_protocol_confusion()
        self.test_encoding_confusion()
        self.test_content_type_confusion()  # NEW
        self.test_host_header_attacks()     # NEW

        print(f"\n  📊 Total discrepancies found: {len(self.discrepancies)}")
        return self.discrepancies
    
    def test_header_confusion(self):
        """Test header parsing discrepancies - EXPANDED"""
        print("\n  🔬 Testing Header Confusion...")

        header_tests = [
            {
                'name': 'Double Content-Type',
                'headers': {
                    'Content-Type': 'application/json',
                    'Content-Type': 'application/x-www-form-urlencoded'
                }
            },
            {
                'name': 'Host Override',
                'headers': {
                    'Host': 'localhost',
                    'X-Forwarded-Host': self.target_url.split('//')[1].split('/')[0]
                }
            },
            {
                'name': 'Method Override',
                'headers': {
                    'X-HTTP-Method-Override': 'GET',
                    'X-Method-Override': 'GET'
                }
            },
            {
                'name': 'Content-Length Mismatch',
                'headers': {
                    'Content-Length': '0',
                    'Transfer-Encoding': 'chunked'
                }
            },
            # EXPANDED: New tests
            {
                'name': 'Transfer-Encoding Chunked Variations',
                'headers': {
                    'Transfer-Encoding': 'chunked, identity'
                }
            },
            {
                'name': 'Range Header Abuse',
                'headers': {
                    'Range': 'bytes=0-0'
                }
            },
            {
                'name': 'Connection Manipulation',
                'headers': {
                    'Connection': 'close, TE',
                    'TE': 'chunked'
                }
            }
        ]
        
        for test in header_tests:
            try:
                response = self.session.get(self.forbidden_endpoint, headers=test['headers'], timeout=5)
                
                # Look for unusual responses indicating discrepancy
                if response.status_code not in [403, 401]:
                    self.discrepancies.append({
                        'type': 'Header Confusion',
                        'test_name': test['name'],
                        'forbidden_url': self.forbidden_endpoint,
                        'headers': test['headers'],
                        'response_code': response.status_code,
                        'severity': 'HIGH' if response.status_code == 200 else 'MEDIUM'
                    })
                    print(f"    ✅ Discrepancy found: {test['name']} → {response.status_code}")
            except Exception as e:
                pass
    
    def test_method_confusion(self):
        """Test HTTP method parsing discrepancies - EXPANDED"""
        print("  🔬 Testing Method Confusion...")

        # EXPANDED: Added WebDAV methods
        methods = ['GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'OPTIONS', 'HEAD', 'TRACE', 'CONNECT', 'PROPFIND', 'MKCOL']
        results = {}
        
        for method in methods:
            try:
                response = self.session.request(method, self.forbidden_endpoint, timeout=5)
                results[method] = response.status_code
                
                # If any method bypasses forbidden
                if response.status_code not in [403, 401, 405]:
                    self.discrepancies.append({
                        'type': 'Method Confusion',
                        'method': method,
                        'forbidden_url': self.forbidden_endpoint,
                        'response_code': response.status_code,
                        'severity': 'HIGH' if response.status_code == 200 else 'MEDIUM'
                    })
                    print(f"    ✅ Discrepancy found: {method} → {response.status_code}")
            except Exception as e:
                results[method] = f"Error: {str(e)}"
    
    def test_path_normalization(self):
        """Test path parsing discrepancies - EXPANDED"""
        print("  🔬 Testing Path Normalization...")

        # Extract path from forbidden endpoint
        parsed = urlparse(self.forbidden_endpoint)
        base_path = parsed.path

        path_variants = [
            base_path,
            base_path + '/',
            base_path + '//',
            base_path + '/.',
            base_path + '/./',
            base_path + '/../' + base_path.split('/')[-1],
            base_path.upper(),
            base_path.replace('/', '//'),
            urllib.parse.quote(base_path),
            urllib.parse.quote(base_path, safe=''),
            base_path + '%00',
            base_path + '?',
            base_path + '#',
            # EXPANDED: New path variants
            base_path.replace('/', '\\'),  # Backslash (Windows style)
            '\ufeff' + base_path,  # UTF-8 BOM
            base_path + ';',  # Path parameter separator
            base_path.replace('/', '%2F'),  # Encoded slash
            base_path + '%0a',  # Newline injection
            base_path.replace('/', '/./'),  # Dot segments
        ]
        
        for variant in path_variants:
            try:
                test_url = f"{parsed.scheme}://{parsed.netloc}{variant}"
                response = self.session.get(test_url, timeout=5, allow_redirects=False)
                
                if response.status_code not in [403, 401]:
                    self.discrepancies.append({
                        'type': 'Path Normalization',
                        'original_path': base_path,
                        'variant': variant,
                        'test_url': test_url,
                        'response_code': response.status_code,
                        'severity': 'HIGH' if response.status_code == 200 else 'MEDIUM'
                    })
                    print(f"    ✅ Discrepancy found: {variant} → {response.status_code}")
            except Exception as e:
                pass
    
    def test_protocol_confusion(self):
        """Test protocol version confusion"""
        print("  🔬 Testing Protocol Confusion...")
        
        # HTTP/1.1 vs HTTP/1.0
        try:
            # Force HTTP/1.0
            import http.client
            parsed = urlparse(self.forbidden_endpoint)
            conn = http.client.HTTPConnection(parsed.netloc) if parsed.scheme == 'http' else http.client.HTTPSConnection(parsed.netloc)
            
            conn.request("GET", parsed.path or '/', headers={'Host': parsed.netloc})
            response = conn.getresponse()
            
            if response.status not in [403, 401]:
                self.discrepancies.append({
                    'type': 'Protocol Confusion',
                    'test': 'HTTP/1.0 vs HTTP/1.1',
                    'forbidden_url': self.forbidden_endpoint,
                    'response_code': response.status,
                    'severity': 'MEDIUM'
                })
                print(f"    ✅ Discrepancy found: HTTP/1.0 → {response.status}")
            
            conn.close()
        except Exception as e:
            pass
    
    def test_encoding_confusion(self):
        """Test encoding confusion between layers"""
        print("  🔬 Testing Encoding Confusion...")
        
        parsed = urlparse(self.forbidden_endpoint)
        base_path = parsed.path
        
        encoding_variants = [
            urllib.parse.quote(base_path),
            urllib.parse.quote(urllib.parse.quote(base_path)),  # Double encoding
            base_path.replace('/', '%2f'),
            base_path.replace('/', '%252f'),  # Double encoded slash
            base_path.replace(' ', '%20').replace('%20', '+'),
            base64.b64encode(base_path.encode()).decode()
        ]
        
        for variant in encoding_variants:
            try:
                test_url = f"{parsed.scheme}://{parsed.netloc}{variant}"
                response = self.session.get(test_url, timeout=5)
                
                if response.status_code not in [403, 401, 400]:
                    self.discrepancies.append({
                        'type': 'Encoding Confusion',
                        'original_path': base_path,
                        'encoded_variant': variant,
                        'test_url': test_url,
                        'response_code': response.status_code,
                        'severity': 'HIGH' if response.status_code == 200 else 'MEDIUM'
                    })
                    print(f"    ✅ Discrepancy found: encoding bypass → {response.status_code}")
            except Exception as e:
                pass

    def test_content_type_confusion(self):
        """Test Content-Type header discrepancies - NEW"""
        print("  🔬 Testing Content-Type Confusion...")

        content_type_tests = [
            {'Content-Type': 'text/plain'},
            {'Content-Type': 'application/json'},
            {'Content-Type': 'application/x-www-form-urlencoded'},
            {'Content-Type': 'multipart/form-data'},
            {'Content-Type': 'application/xml'},
            {'Content-Type': 'text/html'},
            {'Content-Type': 'application/octet-stream'},
        ]

        for headers in content_type_tests:
            try:
                response = self.session.post(self.forbidden_endpoint, headers=headers, data='test', timeout=5)

                if response.status_code not in [403, 401, 405]:
                    self.discrepancies.append({
                        'type': 'Content-Type Confusion',
                        'content_type': headers['Content-Type'],
                        'forbidden_url': self.forbidden_endpoint,
                        'response_code': response.status_code,
                        'severity': 'HIGH' if response.status_code == 200 else 'MEDIUM'
                    })
                    print(f"    ✅ Discrepancy found: {headers['Content-Type']} → {response.status_code}")
            except Exception as e:
                pass

    def test_host_header_attacks(self):
        """Test Host header manipulation - NEW"""
        print("  🔬 Testing Host Header Attacks...")

        parsed = urlparse(self.target_url)
        original_host = parsed.netloc

        host_variations = [
            {'Host': 'localhost'},
            {'Host': '127.0.0.1'},
            {'Host': 'evil.com'},
            {'Host': original_host, 'X-Forwarded-Host': 'evil.com'},
            {'Host': original_host, 'X-Original-Host': 'localhost'},
            {'Host': original_host, 'X-Host': 'evil.com'},
            {'Host': f'{original_host}:80'},
            {'Host': f'{original_host}:443'},
            {'Host': f'{original_host}@evil.com'},
        ]

        for headers in host_variations:
            try:
                response = self.session.get(self.forbidden_endpoint, headers=headers, timeout=5)

                if response.status_code not in [403, 401]:
                    self.discrepancies.append({
                        'type': 'Host Header Attack',
                        'headers': headers,
                        'forbidden_url': self.forbidden_endpoint,
                        'response_code': response.status_code,
                        'severity': 'CRITICAL' if response.status_code == 200 else 'HIGH'
                    })
                    print(f"    ✅ Discrepancy found: {headers} → {response.status_code}")
            except Exception as e:
                pass


class BypassGenerator:
    """
    Generates custom bypass payloads based on discovered discrepancies.
    """
    
    def __init__(self, discrepancies: List[Dict], stack_info: Dict):
        self.discrepancies = discrepancies
        self.stack_info = stack_info
        self.bypasses = []
    
    def generate_all_bypasses(self):
        """Generate bypasses for each discrepancy"""
        print("\n🛠️ Phase 4: Custom Bypass Generation")
        print("=" * 70)
        
        if not self.discrepancies:
            print("  ⚠️ No discrepancies found - no bypasses to generate")
            return []
        
        print(f"  📊 Generating bypasses for {len(self.discrepancies)} discrepancies...")
        
        for discrepancy in self.discrepancies:
            bypass_type = discrepancy['type']
            
            if bypass_type == 'Header Confusion':
                self._generate_header_bypass(discrepancy)
            elif bypass_type == 'Method Confusion':
                self._generate_method_bypass(discrepancy)
            elif bypass_type == 'Path Normalization':
                self._generate_path_bypass(discrepancy)
            elif bypass_type == 'Protocol Confusion':
                self._generate_protocol_bypass(discrepancy)
            elif bypass_type == 'Encoding Confusion':
                self._generate_encoding_bypass(discrepancy)
        
        print(f"\n  ✅ Generated {len(self.bypasses)} bypass techniques")
        return self.bypasses
    
    def _generate_header_bypass(self, discrepancy: Dict):
        """Generate header-based bypass"""
        bypass = {
            'id': f"bypass_{len(self.bypasses) + 1}",
            'type': 'Header Confusion',
            'discrepancy': discrepancy,
            'severity': discrepancy['severity'],
            'method': 'GET',
            'url': discrepancy['forbidden_url'],
            'headers': discrepancy['headers'],
            'description': f"Header confusion bypass: {discrepancy['test_name']}",
            'curl_command': self._generate_curl(discrepancy['forbidden_url'], 'GET', discrepancy['headers'])
        }
        self.bypasses.append(bypass)
    
    def _generate_method_bypass(self, discrepancy: Dict):
        """Generate method-based bypass"""
        bypass = {
            'id': f"bypass_{len(self.bypasses) + 1}",
            'type': 'Method Confusion',
            'discrepancy': discrepancy,
            'severity': discrepancy['severity'],
            'method': discrepancy['method'],
            'url': discrepancy['forbidden_url'],
            'headers': {},
            'description': f"HTTP method bypass using {discrepancy['method']}",
            'curl_command': self._generate_curl(discrepancy['forbidden_url'], discrepancy['method'], {})
        }
        self.bypasses.append(bypass)
    
    def _generate_path_bypass(self, discrepancy: Dict):
        """Generate path-based bypass"""
        bypass = {
            'id': f"bypass_{len(self.bypasses) + 1}",
            'type': 'Path Normalization',
            'discrepancy': discrepancy,
            'severity': discrepancy['severity'],
            'method': 'GET',
            'url': discrepancy['test_url'],
            'headers': {},
            'description': f"Path normalization bypass: {discrepancy['variant']}",
            'curl_command': self._generate_curl(discrepancy['test_url'], 'GET', {})
        }
        self.bypasses.append(bypass)
    
    def _generate_protocol_bypass(self, discrepancy: Dict):
        """Generate protocol-based bypass"""
        bypass = {
            'id': f"bypass_{len(self.bypasses) + 1}",
            'type': 'Protocol Confusion',
            'discrepancy': discrepancy,
            'severity': discrepancy['severity'],
            'method': 'GET',
            'url': discrepancy['forbidden_url'],
            'headers': {},
            'description': f"Protocol confusion bypass: {discrepancy['test']}",
            'curl_command': f"# Use HTTP/1.0: curl --http1.0 '{discrepancy['forbidden_url']}'"
        }
        self.bypasses.append(bypass)
    
    def _generate_encoding_bypass(self, discrepancy: Dict):
        """Generate encoding-based bypass"""
        bypass = {
            'id': f"bypass_{len(self.bypasses) + 1}",
            'type': 'Encoding Confusion',
            'discrepancy': discrepancy,
            'severity': discrepancy['severity'],
            'method': 'GET',
            'url': discrepancy['test_url'],
            'headers': {},
            'description': f"Encoding confusion bypass: {discrepancy['encoded_variant']}",
            'curl_command': self._generate_curl(discrepancy['test_url'], 'GET', {})
        }
        self.bypasses.append(bypass)
    
    def _generate_curl(self, url: str, method: str, headers: Dict) -> str:
        """Generate curl command"""
        cmd = ['curl', '-i']
        
        if method != 'GET':
            cmd.append(f'-X {method}')
        
        for header, value in headers.items():
            cmd.append(f"-H '{header}: {value}'")
        
        cmd.append(f"'{url}'")
        
        return ' '.join(cmd)


class BypassValidator:
    """
    Validates generated bypasses to confirm they work.
    """
    
    def __init__(self, bypasses: List[Dict], session: requests.Session):
        self.bypasses = bypasses
        self.session = session
        self.validated = []
    
    def validate_all(self):
        """Validate all generated bypasses"""
        print("\n🧪 Phase 5: Bypass Validation")
        print("=" * 70)
        
        if not self.bypasses:
            print("  ⚠️ No bypasses to validate")
            return []
        
        print(f"  🔬 Validating {len(self.bypasses)} bypass techniques...")
        
        for bypass in self.bypasses:
            if self._validate_bypass(bypass):
                self.validated.append(bypass)
                print(f"    ✅ Validated: {bypass['type']} - {bypass['description']}")
            else:
                print(f"    ❌ Failed: {bypass['type']}")
        
        print(f"\n  📊 Validation complete: {len(self.validated)}/{len(self.bypasses)} bypasses confirmed")
        return self.validated
    
    def _validate_bypass(self, bypass: Dict) -> bool:
        """Validate a single bypass"""
        try:
            response = self.session.request(
                method=bypass['method'],
                url=bypass['url'],
                headers=bypass.get('headers', {}),
                timeout=10
            )
            
            # Success if we get anything other than 403/401
            if response.status_code not in [403, 401]:
                bypass['validation'] = {
                    'status': 'CONFIRMED',
                    'response_code': response.status_code,
                    'validated_at': datetime.now().isoformat()
                }
                return True
            
            return False
        except Exception as e:
            bypass['validation'] = {
                'status': 'ERROR',
                'error': str(e)
            }
            return False


class ReportGenerator:
    """
    Generates comprehensive reports and exports.
    """
    
    def __init__(self, target_url: str, stack_analyzer: ProgressiveStackAnalyzer, 
                 discrepancies: List[Dict], bypasses: List[Dict]):
        self.target_url = target_url
        self.stack_analyzer = stack_analyzer
        self.discrepancies = discrepancies
        self.bypasses = bypasses
    
    def generate_text_report(self) -> str:
        """Generate human-readable text report"""
        report = f"""
{'=' * 80}
APPLICATION STACK TRACEROUTE v3.0 - INTELLIGENT RECONSTRUCTION
{'=' * 80}

🎯 TARGET: {self.target_url}
📅 SCAN TIME: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

{'=' * 80}
📊 DISCOVERED STACK ARCHITECTURE
{'=' * 80}

"""
        
        # Stack layers
        if self.stack_analyzer.stack['layers']:
            report += "🔗 Processing Chain:\n\n"
            for idx, layer in enumerate(self.stack_analyzer.stack['layers'], 1):
                report += f"  {idx}. {layer['type']}: {layer['component']}\n"
                report += f"     Confidence: {layer['confidence']}/100 ({layer['level']})\n"
                report += f"     Evidence: {', '.join(layer['evidence'])}\n\n"
        else:
            report += "  ⚠️ No stack components detected\n\n"
        
        # Discrepancies
        report += f"\n{'=' * 80}\n"
        report += f"🧪 PARSER DISCREPANCIES FOUND: {len(self.discrepancies)}\n"
        report += f"{'=' * 80}\n\n"
        
        if self.discrepancies:
            for idx, disc in enumerate(self.discrepancies, 1):
                report += f"  {idx}. {disc['type']} - {disc.get('test_name', disc.get('method', 'N/A'))}\n"
                report += f"     Severity: {disc['severity']}\n"
                report += f"     Response: {disc.get('response_code', 'N/A')}\n\n"
        else:
            report += "  ✅ No discrepancies found - stack is consistent\n\n"
        
        # Bypasses
        report += f"\n{'=' * 80}\n"
        report += f"🛠️ GENERATED BYPASSES: {len(self.bypasses)}\n"
        report += f"{'=' * 80}\n\n"
        
        if self.bypasses:
            for idx, bypass in enumerate(self.bypasses, 1):
                report += f"  {idx}. {bypass['type']}\n"
                report += f"     ID: {bypass['id']}\n"
                report += f"     Severity: {bypass['severity']}\n"
                report += f"     Description: {bypass['description']}\n"
                report += f"     Command: {bypass['curl_command']}\n"
                
                if 'validation' in bypass:
                    status = bypass['validation']['status']
                    report += f"     Validation: {status}\n"
                
                report += "\n"
        else:
            report += "  ⚠️ No bypasses generated\n\n"
        
        report += f"\n{'=' * 80}\n"
        report += "📝 NOTES:\n"
        report += f"{'=' * 80}\n\n"
        report += "This report contains validated bypass techniques for authorized security testing.\n"
        report += "Use responsibly and only on targets you have permission to test.\n"
        report += "Export JSON for automation with Exploit Orchestrator tools.\n\n"
        
        return report
    
    def export_json(self, filename: Optional[str] = None) -> str:
        """
        Export data to JSON for orchestration tools.
        FORMAT COMPATIBLE with v2.8 - Works with Burp Suite and smart_crawler
        """
        if not filename:
            domain = urlparse(self.target_url).netloc.replace(':', '_')
            timestamp = int(time.time())
            filename = f"bypasses_{domain}_{timestamp}.json"

        # Extract layer names for infrastructure_chain (v2.8 format)
        infrastructure_chain = []
        for layer in self.stack_analyzer.stack['layers']:
            infrastructure_chain.append(f"{layer['type']}-{layer['component']}")

        # Prepare bypass data (v2.8 format with curl commands)
        export_data = {
            'target_url': self.target_url,
            'scan_timestamp': datetime.now().isoformat(),
            'infrastructure_chain': infrastructure_chain,
            'total_discrepancies': len(self.discrepancies),
            'total_bypasses': len(self.bypasses),
            'bypasses': []
        }

        for idx, bypass in enumerate(self.bypasses, 1):
            bypass_entry = {
                'id': f"bypass_{idx}",
                'type': bypass.get('type', 'Unknown'),
                'target': bypass.get('url', self.target_url),
                'description': bypass.get('description', ''),
                'validated': bypass.get('validation', {}).get('status') == 'CONFIRMED',
                'curl_data': bypass.get('curl_data', {}),
                'payload': str(bypass.get('payload', ''))
            }

            # Generate curl command (v2.8 style)
            curl_command = self._generate_curl_command(bypass_entry)
            bypass_entry['curl_command'] = curl_command

            export_data['bypasses'].append(bypass_entry)

        # Save to JSON file
        with open(filename, 'w') as f:
            json.dump(export_data, f, indent=2, default=str)

        print(f"\n💾 JSON Export (v2.8 compatible): {filename}")
        print(f"   Total bypasses: {len(export_data['bypasses'])}")
        print(f"   Validated: {len([b for b in export_data['bypasses'] if b['validated']])}")

        return filename

    def _generate_curl_command(self, bypass_entry: Dict) -> str:
        """Generate curl command for a specific bypass (v2.8 format)"""
        base_url = self.target_url
        curl_data = bypass_entry.get('curl_data', {})

        if not curl_data:
            # Fallback: simple command based on bypass type
            return f"curl -i '{bypass_entry.get('target', base_url)}'"

        method = curl_data.get('method', 'GET')

        # Build curl command
        cmd_parts = ['curl', '-i']

        # Add method
        if method != 'GET':
            cmd_parts.append(f'-X {method}')

        # Add headers
        headers = curl_data.get('headers', {})
        for header, value in headers.items():
            if not header.startswith(':'):  # Skip HTTP/2 pseudo-headers
                cmd_parts.append(f'-H "{header}: {value}"')

        # Add data
        if 'data' in curl_data:
            if isinstance(curl_data['data'], str):
                cmd_parts.append(f'-d "{curl_data["data"]}"')
            elif isinstance(curl_data['data'], dict):
                cmd_parts.append(f"-d '{json.dumps(curl_data['data'])}'")

        # Add path/query
        path = curl_data.get('path', '')
        query = curl_data.get('query', '')
        full_url = f"{base_url}{path}{query}"

        cmd_parts.append(f'"{full_url}"')

        # Add notes
        if 'note' in curl_data:
            return f"# Note: {curl_data['note']}\n{' '.join(cmd_parts)}"

        return ' '.join(cmd_parts)


class ApplicationTraceroute:
    """
    Main orchestrator for the complete analysis workflow.
    """
    
    def __init__(self, target_url: str, forbidden_endpoint: Optional[str] = None, 
                 skip_forbidden_tests: bool = False):
        self.target_url = target_url.rstrip('/')
        self.forbidden_endpoint = forbidden_endpoint
        self.skip_forbidden_tests = skip_forbidden_tests
        
        # Initialize session
        self.session = requests.Session()
        self.session.verify = False
        
        # Components
        self.stack_analyzer = ProgressiveStackAnalyzer(target_url)
        self.stack_analyzer.session = self.session  # Share session
        
        self.forbidden_finder = ForbiddenEndpointFinder(target_url, self.session)
        self.discrepancy_tester = None
        self.bypass_generator = None
        self.bypass_validator = None
        self.report_generator = None
    
    async def run_full_analysis(self):
        """Run complete analysis workflow"""
        print("\n" + "=" * 80)
        print("🔬 APPLICATION STACK TRACEROUTE v3.0")
        print("🎯 Intelligent Stack Reconstruction & Bypass Generation")
        print("=" * 80)
        print(f"\n🎯 Target: {self.target_url}\n")
        
        # Phase 0: Find Forbidden Endpoint
        if not self.skip_forbidden_tests:
            self.forbidden_endpoint = self.forbidden_finder.find(self.forbidden_endpoint)
        
        # Phase 1: Send Baseline Request
        print("\n🔍 Phase 1: Baseline Analysis")
        print("=" * 70)
        baseline_response = self.stack_analyzer.send_baseline_request()
        print(f"  ✅ Baseline request completed (Status: {baseline_response.status_code})")
        
        # Phase 2: Progressive Stack Fingerprinting
        print("\n🔍 Phase 2: Progressive Stack Fingerprinting")
        print("=" * 70)
        
        # 2a: Header Timeline Analysis
        timeline = self.stack_analyzer.analyze_header_timeline(baseline_response)
        print(f"  ✅ Header timeline analyzed: {len(timeline)} processing hops detected")
        
        # 2b: Deep Fingerprinting
        self.stack_analyzer.progressive_fingerprinting(baseline_response)
        
        # 2c: Correlate Stack
        self.stack_analyzer.correlate_stack()
        
        # Phase 3: Discrepancy Testing
        if self.forbidden_endpoint and not self.skip_forbidden_tests:
            self.discrepancy_tester = DiscrepancyTester(
                self.target_url, 
                self.forbidden_endpoint, 
                self.session,
                self.stack_analyzer
            )
            discrepancies = self.discrepancy_tester.test_all_discrepancies()
        else:
            print("\n⚠️ Phase 3: Skipping discrepancy testing (no forbidden endpoint)")
            discrepancies = []
        
        # Phase 4: Bypass Generation
        self.bypass_generator = BypassGenerator(
            discrepancies,
            self.stack_analyzer.stack
        )
        bypasses = self.bypass_generator.generate_all_bypasses()
        
        # Phase 5: Bypass Validation
        self.bypass_validator = BypassValidator(bypasses, self.session)
        validated_bypasses = self.bypass_validator.validate_all()
        
        # Phase 6: Report Generation
        self.report_generator = ReportGenerator(
            self.target_url,
            self.stack_analyzer,
            discrepancies,
            validated_bypasses
        )
        
        # Generate text report
        text_report = self.report_generator.generate_text_report()
        
        # Export JSON
        json_file = self.report_generator.export_json()
        
        # Save text report
        report_filename = f"traceroute_{int(time.time())}.txt"
        with open(report_filename, 'w') as f:
            f.write(text_report)
        
        print(f"\n📄 Text Report: {report_filename}")
        
        # Print summary
        print("\n" + "=" * 80)
        print("📊 ANALYSIS COMPLETE")
        print("=" * 80)
        print(f"  Stack Layers: {len(self.stack_analyzer.stack['layers'])}")
        print(f"  Discrepancies: {len(discrepancies)}")
        print(f"  Bypasses Generated: {len(bypasses)}")
        print(f"  Bypasses Validated: {len(validated_bypasses)}")
        print("\n" + "=" * 80)
        
        return text_report


def main():
    import argparse
    
    parser = argparse.ArgumentParser(
        description='Application Stack Traceroute v3.0 - Intelligent Stack Reconstruction',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python app_traceroute_v3.py https://target.com
  python app_traceroute_v3.py https://target.com --forbidden-endpoint https://target.com/admin
  python app_traceroute_v3.py https://target.com --skip-forbidden-tests
        """
    )
    
    parser.add_argument('target', help='Target URL to analyze')
    parser.add_argument(
        '--forbidden-endpoint',
        help='Known 403/401 endpoint for bypass testing (e.g. https://target.com/admin)'
    )
    parser.add_argument(
        '--skip-forbidden-tests',
        action='store_true',
        help='Skip tests requiring forbidden endpoint'
    )
    
    args = parser.parse_args()
    
    # Run analysis
    tracer = ApplicationTraceroute(
        args.target,
        forbidden_endpoint=args.forbidden_endpoint,
        skip_forbidden_tests=args.skip_forbidden_tests
    )
    
    # Use asyncio for async operations
    asyncio.run(tracer.run_full_analysis())


if __name__ == "__main__":
    main()